"""
StatGenie Configuration Module
Centralized settings for models, feature flags, limits, and environment variables.
"""
import os
from typing import Optional
from dataclasses import dataclass
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()


@dataclass
class ModelConfig:
    """AI Model Configuration"""
    # Gemini model names
    GEMINI_PRIMARY: str = "gemini-2.0-flash-exp"
    GEMINI_FALLBACK: str = "gemini-1.5-flash"
    GEMINI_VISION: str = "gemini-2.0-flash-exp"
    
    # Model parameters
    TEMPERATURE: float = 0.6
    MAX_OUTPUT_TOKENS: int = 8192
    TOP_P: float = 0.95
    TOP_K: int = 40
    
    # Retry settings
    MAX_RETRIES: int = 3
    RETRY_DELAY: float = 1.0


@dataclass
class StorageConfig:
    """Job and Data Storage Configuration"""
    # Redis settings
    REDIS_HOST: str = os.getenv("REDIS_HOST", "localhost")
    REDIS_PORT: int = int(os.getenv("REDIS_PORT", "6379"))
    REDIS_DB: int = int(os.getenv("REDIS_DB", "0"))
    REDIS_PASSWORD: Optional[str] = os.getenv("REDIS_PASSWORD")
    REDIS_SSL: bool = os.getenv("REDIS_SSL", "false").lower() == "true"
    
    # Job TTL (time-to-live)
    JOB_TTL_SECONDS: int = int(os.getenv("JOB_TTL_SECONDS", "3600"))  # 1 hour default
    
    # Compression
    USE_COMPRESSION: bool = True
    COMPRESSION_THRESHOLD_BYTES: int = 1024  # Compress if larger than 1KB
    
    # Fallback to in-memory if Redis unavailable
    FALLBACK_TO_MEMORY: bool = True


@dataclass
class FileConfig:
    """File Upload and Processing Configuration"""
    UPLOAD_FOLDER: str = "uploads/"
    MAX_FILE_SIZE_MB: int = int(os.getenv("MAX_FILE_SIZE_MB", "16"))
    MAX_CONTENT_LENGTH: int = MAX_FILE_SIZE_MB * 1024 * 1024
    
    ALLOWED_EXTENSIONS: tuple = (
        ".csv", ".xls", ".xlsx", ".json",
        ".txt", ".pdf", ".doc", ".docx",
        ".png", ".jpg", ".jpeg", ".bmp", ".tiff"
    )
    
    # Cleanup settings
    AUTO_CLEANUP_UPLOADS: bool = True
    CLEANUP_INTERVAL_SECONDS: int = 300  # Clean every 5 minutes


@dataclass
class AnalysisConfig:
    """Data Analysis Pipeline Configuration"""
    # Chart generation
    MAX_CHARTS: int = 8
    CHART_WIDTH: int = 800
    CHART_HEIGHT: int = 600
    CHART_SCALE: int = 2
    
    # KPI limits
    MAX_NUMERIC_COLS_FOR_KPI: int = 5
    MAX_CATEGORICAL_COLS_FOR_SUMMARY: int = 10
    
    # Feature engineering
    DEFAULT_SCALER: str = "standard"  # Options: standard, minmax, robust
    DEFAULT_ENCODER: str = "onehot"   # Options: onehot, label, target
    
    # Statistical tests
    SIGNIFICANCE_LEVEL: float = 0.05
    
    # Outlier detection
    OUTLIER_METHOD: str = "iqr"  # Options: iqr, zscore, isolation_forest
    IQR_MULTIPLIER: float = 1.5
    ZSCORE_THRESHOLD: float = 3.0


@dataclass
class FilterConfig:
    """Filter and Slicer Configuration"""
    MAX_CATEGORICAL_UNIQUE: int = 50  # Max unique values for categorical slicer
    PREVIEW_SAMPLE_SIZE: int = 10000  # Sample size for filter preview
    
    # Supported operators
    NUMERIC_OPERATORS: tuple = ("eq", "ne", "lt", "lte", "gt", "gte", "between")
    CATEGORICAL_OPERATORS: tuple = ("eq", "ne", "in", "nin")
    DATE_OPERATORS: tuple = ("eq", "ne", "lt", "lte", "gt", "gte", "between")


@dataclass
class ExportConfig:
    """Export Configuration"""
    PDF_LOGO_PATH: str = "statgenie_logo.png"
    PDF_FOOTER_TEXT: str = "Generated by StatGenie"
    
    # Export formats
    SUPPORTED_FORMATS: tuple = ("pdf", "html", "xlsx", "png_zip")
    
    # Image export
    IMAGE_FORMAT: str = "png"
    IMAGE_DPI: int = 300


@dataclass
class SecurityConfig:
    """Security and Rate Limiting Configuration"""
    # API Key (if implementing auth)
    API_KEY_HEADER: str = "X-API-Key"
    REQUIRE_AUTH: bool = os.getenv("REQUIRE_AUTH", "false").lower() == "true"
    
    # Rate limiting
    ENABLE_RATE_LIMIT: bool = os.getenv("ENABLE_RATE_LIMIT", "false").lower() == "true"
    RATE_LIMIT_PER_MINUTE: int = int(os.getenv("RATE_LIMIT_PER_MINUTE", "60"))
    
    # Input sanitization
    MAX_PROMPT_LENGTH: int = 5000
    SANITIZE_USER_INPUT: bool = True


@dataclass
class LoggingConfig:
    """Logging Configuration"""
    LOG_LEVEL: str = os.getenv("LOG_LEVEL", "INFO")
    LOG_FORMAT: str = "json"  # Options: json, text
    LOG_FILE: Optional[str] = os.getenv("LOG_FILE")
    
    # Structured logging fields
    INCLUDE_TIMESTAMP: bool = True
    INCLUDE_REQUEST_ID: bool = True


@dataclass
class FeatureFlags:
    """Feature Toggle Flags"""
    # Core features
    ENABLE_FEATURE_ENGINEERING: bool = True
    ENABLE_STATISTICAL_TESTS: bool = True
    ENABLE_AI_INSIGHTS: bool = True
    
    # Advanced features (v3.5+)
    ENABLE_RAG_CHAT: bool = False  # Not yet implemented
    ENABLE_COPILOT: bool = False   # Not yet implemented
    ENABLE_MULTI_SOURCE_IMPORT: bool = False  # Not yet implemented
    
    # Experimental
    ENABLE_ASYNC_PROCESSING: bool = False
    ENABLE_CHART_EXPLAIN: bool = False


class Config:
    """Master Configuration Class"""
    
    def __init__(self):
        # API Keys
        self.GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
        if not self.GEMINI_API_KEY:
            raise ValueError("❌ GEMINI_API_KEY environment variable not set")
        
        # Sub-configurations
        self.model = ModelConfig()
        self.storage = StorageConfig()
        self.file = FileConfig()
        self.analysis = AnalysisConfig()
        self.filter = FilterConfig()
        self.export = ExportConfig()
        self.security = SecurityConfig()
        self.logging = LoggingConfig()
        self.features = FeatureFlags()
        
        # Application settings
        self.APP_NAME = "StatGenie"
        self.APP_VERSION = "3.6.0-dev"
        self.DEBUG = os.getenv("DEBUG", "true").lower() == "true"
        self.PORT = int(os.getenv("PORT", "8080"))
        self.HOST = os.getenv("HOST", "0.0.0.0")
    
    def validate(self):
        """Validate configuration settings"""
        errors = []
        
        # Check file size limits
        if self.file.MAX_FILE_SIZE_MB <= 0:
            errors.append("MAX_FILE_SIZE_MB must be positive")
        
        # Check Redis connection if not using fallback
        if not self.storage.FALLBACK_TO_MEMORY:
            if not self.storage.REDIS_HOST:
                errors.append("REDIS_HOST required when FALLBACK_TO_MEMORY=False")
        
        # Check TTL
        if self.storage.JOB_TTL_SECONDS <= 0:
            errors.append("JOB_TTL_SECONDS must be positive")
        
        if errors:
            raise ValueError(f"Configuration errors: {', '.join(errors)}")
        
        return True
    
    def to_dict(self) -> dict:
        """Export configuration as dictionary (for debugging)"""
        return {
            "app": {
                "name": self.APP_NAME,
                "version": self.APP_VERSION,
                "debug": self.DEBUG,
                "host": self.HOST,
                "port": self.PORT
            },
            "model": self.model.__dict__,
            "storage": {k: v for k, v in self.storage.__dict__.items() if k != "REDIS_PASSWORD"},
            "file": self.file.__dict__,
            "analysis": self.analysis.__dict__,
            "filter": self.filter.__dict__,
            "export": self.export.__dict__,
            "security": {k: v for k, v in self.security.__dict__.items() if "KEY" not in k},
            "logging": self.logging.__dict__,
            "features": self.features.__dict__
        }


# Global configuration instance
config = Config()

# Validate on import
try:
    config.validate()
except ValueError as e:
    print(f"⚠️  Configuration warning: {e}")
